/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package people;

/**
 *
 * @author Acer
 */

import gui.Person;
import java.awt.Color;
import java.awt.Graphics;
import java.util.Random;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.*;  
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;


public class JavaAnimation extends javax.swing.JFrame {
    
    private static final String username = "root";
    private static final String password = "Monh123456@";
    private static final String dataConn = "jdbc:mysql://localhost:3306/my";
    
    public List<Person> person1 = new ArrayList<Person>();
    public List<Person> person2 = new ArrayList<Person>();
    public List<Person> person3 = new ArrayList<Person>();
    public List<Person> person4 = new ArrayList<Person>();
    public List<Person> person5 = new ArrayList<Person>();
    
    
    Graphics g1, g2, g3, g4, g5;
    Thread animationThread;
    
    static final int MAX_X = 488;
    static final int MAX_Y = 388;
    
    /**
     * Creates new form Form
     */
    public JavaAnimation() {
        initComponents();
        
        g1 = panelCanvas.getGraphics();
        g2 = panelCanvas.getGraphics();
        g3 = panelCanvas.getGraphics();
        g4 = panelCanvas.getGraphics();
        g5 = panelCanvas.getGraphics();

        panelCanvas.paintComponents(g1);
        panelCanvas.paintComponents(g2);
        
        panelCanvas.paintComponents(g3);
        
        panelCanvas.paintComponents(g4);
        
        panelCanvas.paintComponents(g5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panelCanvas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Эхлэх");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Зогсоох");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        panelCanvas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout panelCanvasLayout = new javax.swing.GroupLayout(panelCanvas);
        panelCanvas.setLayout(panelCanvasLayout);
        panelCanvasLayout.setHorizontalGroup(
            panelCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );
        panelCanvasLayout.setVerticalGroup(
            panelCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jButton1)
                .addGap(137, 137, 137)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(panelCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(panelCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
       
      
        animationThread = new Thread(new Runnable() {
         
            Random r = new Random();
            
            Color[] colorList = {Color.red, Color.blue, Color.orange, Color.BLACK, Color.GRAY};
            @Override
            public void run() {
                
              
                
                try {
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    Connection conn = DriverManager.getConnection(dataConn, username, password);
                    Statement statement = conn.createStatement();
                    String sql = "select * from data1 ";
                    ResultSet rs = statement.executeQuery(sql);

                           

                     while (rs.next()) {
                
                           int x = rs.getInt("x");
                           int y = rs.getInt("y");
                           int i = r.nextInt(colorList.length);
                            
                          switch(rs.getInt("T_id")) {
                              case 0:
                                  person1.add(new Person(rs.getInt("x"), rs.getInt("y")));
                                 break;
                                case 1:
                                 person2.add(new Person(rs.getInt("x"), rs.getInt("y")));
                                   break;
                                case 2:
                                   person3.add(new Person(rs.getInt("x"), rs.getInt("y")));
                                   break;
                               case 3:
                                   person4.add(new Person(rs.getInt("x"), rs.getInt("y")));
                                   break;
                                case 4:
                                   person5.add(new Person(rs.getInt("x"), rs.getInt("y")));
                                   break;
                         }
                           
               
                     }
                     

                }
                catch (Exception e) {

                }
                
                List<List> lists = Arrays.asList(person1,person2,person3, person4, person5); 
                int max = 0;
                for (List list : lists) {
                    if (list.size() > max) {
                        max = list.size();
                       
                    }
                }
                  for(int i= 0; i< max - 1 ; i++) {
                           System.out.println(i);
                            boolean inBounds1 = (i >= 0) && (i < person1.size());
                            boolean inBounds2 = (i >= 0) && (i < person2.size());
                            boolean inBounds3 = (i >= 0) && (i < person3.size());
                            boolean inBounds4 = (i >= 0) && (i < person4.size());
                            boolean inBounds5 = (i >= 0) && (i < person5.size());
                            
                          if(inBounds1)
                           {
                               g1.setColor(colorList[0]);
                                g1.fillOval(person1.get(i).x, person1.get(i).y, 50, 50);
                          }
                           if(inBounds2)
                           {
                                g2.setColor(colorList[1]);
                                g2.fillOval(person2.get(i).x, person2.get(i).y, 50, 50);
                           }
                           if(inBounds3)
                           {
                           g3.setColor(colorList[2]);
                           g3.fillOval(person3.get(i).x, person3.get(i).y, 50, 50);
                           }
                            if(inBounds4)
                           {
                           g4.setColor(colorList[3]);
                           g4.fillOval(person4.get(i).x, person4.get(i).y, 50, 50);
                           }
                            if(inBounds5)
                           {
                               g5.setColor(colorList[4]);
                               g5.fillOval(person5.get(i).x, person5.get(i).y, 50, 50);
                           }
                           
                          try {
                               Thread.sleep(200);
                               panelCanvas.repaint();
                               Thread.sleep(300);
                          }
                           catch(Exception e){
                               System.err.println("" +e.getMessage());
                            }
                          
                         
                          }
          
             
                
//                 for (Person data : person1) {
//                     System.out.print(person1.size());
//                    System.out.format(" %2d %2d\n", data.x, data.y);
//                  }
                               
            }
        });
        animationThread.start();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaAnimation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaAnimation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaAnimation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaAnimation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaAnimation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel panelCanvas;
    // End of variables declaration//GEN-END:variables
}


